import {  } from './../constants';
import * as constants from '../constants';
import { createAsyncThunk, createSlice } from '@reduxjs/toolkit';
import { RootState } from '../../app/store';
import { getRobots, IRobot, IGetRobotsResponse } from './robotsAPI';

export interface IRobotsState {
  data: {
    allRobots: IRobot[];
  },
  status: typeof constants.IDLE | typeof constants.PENDING | typeof constants.GET_SESSION_SUCCESS | typeof constants.GET_SESSION_FAILURE | typeof constants.SOMETHING_BROKE
    | typeof constants.SERVER_ERROR | typeof constants.GET_ROBOTS_SUCCESS | typeof constants.GET_ROBOTS_FAILURE;
}

export const robotsInitialState: IRobotsState = {
  data: {
    allRobots: []
  },
  status: 'idle',
};

/**
 * creates AsyncThunk to be used with createSlice to create getSession actions / reducers
 */
export const getRobotsAsync = createAsyncThunk(
  'auth/getRobots',
  async (token: string) => {
    const response: IGetRobotsResponse = await getRobots(token)
    return response
  }
)

/**
 * create a slice for robots data services
 */
export const robotsSlice = createSlice({
  name: 'robots',
  initialState: robotsInitialState,
  // The `reducers` field lets us define reducers and generate associated actions
  reducers: {
    resetRobots: (state) => {
      state.data = robotsInitialState.data
      state.status = robotsInitialState.status
    }
  },
  // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // including actions generated by createAsyncThunk or in other slices.
  extraReducers: (builder) => {
    builder
      // ----- getRobotsAsync
      .addCase(getRobotsAsync.pending, (state) => {
        state.status = constants.PENDING;
      })
      .addCase(getRobotsAsync.fulfilled, (state, action) => {
        const { data, status } = action.payload

        if (status === 200) {
          state.status = constants.GET_ROBOTS_SUCCESS
          state.data.allRobots = data
        }
        if (status >= 400 && status < 500) {
          // TODO: ideally we have better reasons why the login failed
          // ie: bad email, or bad password
          state.status = constants.GET_ROBOTS_FAILURE
        }
        if (status > 500) {
          state.status = constants.SERVER_ERROR
        }
      })
      .addCase(getRobotsAsync.rejected, (state) => {
        state.status = constants.SOMETHING_BROKE
      })
  },
});

// export actions generated by createSlice()
export const { resetRobots } = robotsSlice.actions

// The function below is called a selector and allows us to select a value from
// the state. Selectors can also be defined inline where they're used instead of
// in the slice file. For example: `useSelector((state: RootState) => state.counter.value)`
export const selectAllRobotsData = (state: RootState): IRobot[] => state.robots.data.allRobots
export const selectRobotsStatus = (state: RootState): string => state.robots.status

export default robotsSlice.reducer;
